project_id = "yucdpvnmcuokemhqpnvz"

[functions.dodo-webhook]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false

[functions.test-dodo-payments]
verify_jwt = false

[functions.verify-dodo-config]
verify_jwt = false

[functions.gemini-analyze]
verify_jwt = false

[functions.log-analytics]
verify_jwt = false